const express = require('express');
const router = express.Router();
const tareasController = require('../controllers/tareasController');
const { authenticate } = require('../middleware/auth');
router.post('/', authenticate, tareasController.crearTarea);
router.get('/', authenticate, tareasController.obtenerTareas);
router.get('/:id', authenticate, tareasController.obtenerTareaPorId);
router.put('/:id', authenticate, tareasController.actualizarTarea);
router.delete('/:id', authenticate, tareasController.eliminarTarea);
router.get('/estado/:estado', authenticate, tareasController.obtenerTareasPorEstado);
module.exports = router;